# Generated by Django 5.2 on 2025-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafariAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_sound', models.CharField(max_length=10)),
                ('sound_position', models.CharField(choices=[('beginning', 'Beginning'), ('middle', 'Middle'), ('ending', 'Ending')], max_length=20)),
                ('environment', models.CharField(choices=[('jungle', 'Jungle'), ('savanna', 'Savanna'), ('ocean', 'Ocean'), ('arctic', 'Arctic')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'safari_animals',
                'indexes': [models.Index(fields=['target_sound'], name='safari_anim_target__98894e_idx'), models.Index(fields=['difficulty_level'], name='safari_anim_difficu_ce9fe8_idx'), models.Index(fields=['environment'], name='safari_anim_environ_e95486_idx'), models.Index(fields=['sound_position'], name='safari_anim_sound_p_257613_idx'), models.Index(fields=['target_sound', 'difficulty_level', 'environment'], name='safari_anim_target__4a6511_idx')],
            },
        ),
    ]
