# Generated by Django 5.2 on 2025-04-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabificationword',
            options={'ordering': ['word']},
        ),
        migrations.AddIndex(
            model_name='syllabificationword',
            index=models.Index(fields=['difficulty_level'], name='syllabifica_difficu_89a46c_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabificationword',
            index=models.Index(fields=['word'], name='syllabifica_word_085d6c_idx'),
        ),
    ]
