# Generated by Django 5.2 on 2025-04-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabification', '0002_alter_syllabificationword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabificationword',
            name='category',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Colors', 'Colors'), ('Food Items', 'Food Items'), ('Action Words', 'Action Words'), ('Places', 'Places'), ('Feelings', 'Feelings'), ('Common Objects', 'Common Objects'), ('Numbers', 'Numbers'), ('Custom Words', 'Custom Words'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AddIndex(
            model_name='syllabificationword',
            index=models.Index(fields=['category'], name='syllabifica_categor_e65a78_idx'),
        ),
    ]
