# Generated by Django 5.2.5 on 2025-08-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabification', '0003_syllabificationword_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyllabificationWord',
        ),
    ]
