# Generated by Django 5.2.5 on 2025-08-31 07:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('syllabification', 'Syllabification'), ('phonemics', 'Phonemics'), ('phonics', 'Phonics'), ('sentence_formation', 'Sentence Formation')], max_length=50)),
                ('activity_type', models.CharField(max_length=100)),
                ('question_data', models.JSONField()),
                ('user_answer', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('time_spent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('challenge_level', models.CharField(blank=True, max_length=50)),
                ('learning_focus', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('syllabification', 'Syllabification'), ('phonemics', 'Phonemics'), ('phonics', 'Phonics'), ('sentence_formation', 'Sentence Formation')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('average_time_per_question', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'module', 'difficulty')},
            },
        ),
    ]
